name: Mise en production

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Environnement à utiliser'
        required: true
        default: 'dev'

jobs:
  deploye-env:
    runs-on: ubuntu-latest
    steps:
      - name: Start Workflow
        run: echo "Workflow démarré sur ${{ github.ref }}"
      - name: Checkout
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v4.1.1
