name: Mise en production

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Environnement à utiliser'
        required: true
        default: 'dev'

jobs:
  get-source:
    runs-on: ubuntu-latest
    steps:
      - name: Start Workflow
        run: echo "Workflow démarré"
